sudo: required

language: cpp

services:
    - docker

install:
    - docker build -f Dockerfile.alpine -t phptdlib_alpine .

script:
    - docker run --entrypoint /usr/bin/php phptdlib_alpine -m | grep tdlib
    # - docker run --entrypoint /usr/bin/pvs-studio-analyzer credentials ${PVS_USER} ${PVS_PASSWORD} -O ~/phptdlib/PVS-Studio.lic
    # - docker run --entrypoint /usr/bin/pvs-studio-analyzer analyze -l ~/phptdlib/PVS-Studio.lic -o ~/phptdlib/project.log -e ~/phptdlib/modules -j5
    # - docker run --entrypoint /usr/bin/plog-converter -a GA:1,2 -t tasklist -o ~/phptdlib/project.tasks ~/phptdlib/project.log
